### PR TITLE
Support the runner context of gitea act

### PR DESCRIPTION
**Pull request by josedev-union**
#### Summary
fix https://github.com/sigstore/cosign-installer/issues/146

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thank you

**Comment by cpanato** [comment]
can you try the main branch and report back here if that is working for you? @josedev-union

**Comment by josedev-union** [comment]
> can you try the main branch and report back here if that is working for you? @josedev-union

@cpanato it works.

**Comment by cpanato** [comment]
will be included in the next release

**Pull request merged**
