### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by jauderho**
#### Summary

Enable Dependabot

#### Ticket Link

Fixes

This adds .github/dependabot.yml and enables Dependabot monitoring of GitHub Actions versions. Dependabot will create new PRs as necessary.

#### Release Note

```release-note

```

Signed-off-by: Jauder Ho <jauderho@users.noreply.github.com>

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks!

**Comment by bobcallaway** [comment]
FYI this merge broke the action from running:

https://github.com/sigstore/cosign-installer/actions/runs/1811197864

[Invalid workflow file: .github/workflows/test-action.yml#L263](https://github.com/sigstore/cosign-installer/actions/runs/1808332461/workflow)
```You have an error in your yaml syntax on line 263```

**Comment by jauderho** [comment]
Hmm. Let me take a look in a bit.

**Comment by bobcallaway** [comment]
> @bobcallaway
> 
> Looks like I incorrectly created .github/workflows/dependabot.yml initially when it was supposed to be .github/dependabot.yml. That got fixed but there was a separate indent issue which it looks like you have fixed.
> 
> This particular PR did not touch .github/workflows/test-action.yml though.
> 
> I think [fbb87b5](https://github.com/sigstore/cosign-installer/commit/fbb87b50cedf3cea83077f49eb0aa9427c07c6e3) broke .github/workflows/test-action.yml but it is odd since it's the first time I have seen an issue from using https://app.stepsecurity.io/ to convert workflows to use commit hashes.
> 
> Thanks for fixing it and I'll make sure to verify any indent issues going forward.

no problem, thanks for checking into it :)

**Pull request merged**
