### PR TITLE
install consign in the .cosing directory to not mess with any other directories

### PR DESCRIPTION
**Pull request by cpanato**
Install cosign in its own directory and add CI tests to validate if the checkout-ed repo remains clean

Fixes: https://github.com/sigstore/cosign-installer/issues/23

### CODE REVIEW

**Comment by cpanato** [comment]
/cc @caarlos0 @dirien 

did some tests locally and looks better now

**Review by caarlos0 — APPROVED** [review]

**Review by dirien — APPROVED** [review]
Very nice. I like the switch to remote pub key rather downloading it.

**Comment by cpanato** [comment]
gently ping @mbestavros

**Review by imjasonh — APPROVED** [review]

**Review by mbestavros — APPROVED** [review]
LGTM!

**Comment by dirien** [comment]
Yeah! 🥂

**Comment by dirien** [comment]
@cpanato, will you release this with the 1.2.0 update?

**Comment by cpanato** [comment]
> @cpanato, will you release this with the 1.2.0 update?

yes sir!

**Comment by dirien** [comment]
> > @cpanato, will you release this with the 1.2.0 update?
> 
> yes sir!

Not every hero wears a cape!

**Pull request merged**
